Feature/endpoint my instructions pvd 123
Goader/planty pull request #19
Opened 2022-05-07 18:08 UTC by pawlew2k

MyInstructionsView based on PlantsView with get and put method (still do not understand why we don't want to make delete possibility in this view but there was no 'delete' button on figma)

2022-05-08 17:02 UTC, Kamil153 requested changes

2022-05-08 19:52 UTC, pawlew2k commented on backend/planty/dashboard/urls.py
> +    path('my_instructions/', MyInstructionsView.as_view(), name='MyInstructionsView')
zgodnie z figmą będą dwa widoki do:
- tylko moich instrukcji z możliwością update
- do moich i najpopularniejszych tylko pod select
mogę nazwać urle:
"my_instructions/" i "popular_instructions" lub "instructions/my" i "instructions/popular"
chyba że masz lepszą propozycję?

2022-05-08 19:54 UTC, pawlew2k commented on backend/planty/dashboard/views.py
> +        instruction.fertilizing = data.get('species', instruction.fertilizing)
no tak XD, już poprawione

2022-05-08 20:35 UTC, pawlew2k commented on backend/planty/dashboard/views.py
> +        for instruction in instructions.iterator():
iterator() usunięty

2022-05-08 20:38 UTC, pawlew2k commented on backend/planty/dashboard/views.py
> +        for instruction in instructions.iterator():
list comprehension zaoszczędziłoby kilka linijek, ale w takiej formie lepiej widać jaki format jsona zwraca, więc chyba zostanę przy tym co jest

2022-05-08 20:38 UTC, pawlew2k commented on backend/planty/dashboard/views.py
> +        for instruction in instructions.iterator():
list comprehension zaoszczędziłoby kilka linijek, ale w takiej formie lepiej widać jaki format jsona zwraca, więc chyba zostanę przy tym co jest

2022-05-10 15:35 UTC, Goader submitted a review, later dismissed
LGTM, jedynie zmieniłbym ścieżkę endpoint'a

2022-05-11 17:28 UTC, pawlew2k commented on backend/planty/dashboard/urls.py
> +    path('my_instructions/', MyInstructionsView.as_view(), name='MyInstructionsView')
finalnie zmienione na `dashboard/instructions/`

2022-05-11 18:20 UTC, Goader requested changes
Tyle że `dashboard/` w ścieżce bierze się od tego, że juz jesteś w appce, która nazywa się `dashboard/`, więc wystarczy tylko `instructions/` podać

2022-05-11 19:27 UTC, closed without merging