Feature/django service
Goader/planty pull request #2
Opened 2022-04-08 13:17 UTC by pawlew2k

django service

2022-04-08 13:28 UTC, piotrkica requested changes
Overall good job, but fix that one line

2022-04-08 13:28 UTC, piotrkica commented on backend/mysite/mysite/settings.py
> +TIME_ZONE = 'UTC'
replace timezone to CET

2022-04-08 13:58 UTC, Goader requested changes
Mostly good, configuration needs a little refactoring

2022-04-08 13:58 UTC, Goader commented on backend/mysite/mysite/settings.py
> +SECRET_KEY = 'django-insecure-x+#^39p!33-aaql66y7qbjz(@k-c36k0o50c@c)a14g)5^4(6x'
What is that key for? And shouldn't it be hidden somewhere? For example, in `.env`

2022-04-08 13:58 UTC, Goader commented on backend/mysite/mysite/settings.py
> +DEBUG = True
It's better to read this from the environment variable for easy configuration in production

2022-04-08 13:58 UTC, Goader commented on backend/mysite/mysite/settings.py
> +        'ENGINE': 'django.db.backends.sqlite3',
We use MongoDB, so we should look for the engine explicitly for Mongo and specify it here

2022-04-12 19:29 UTC, piotrkica commented
Replace "mysite" occurrences (both directory names and docstrings) to "planty"

2022-04-13 18:01 UTC, merged