Get endpoint for single plant [PVD-128]
Goader/planty pull request #20
Opened 2022-05-08 10:55 UTC by piotrkica

Some notes:
- should i find better name since PlantView and PlantsView is almost indentical? (e.g. SinglePlantView?)
- we could use new plant.values() method in PlantsView GET method
- that dashboard file is getting too big we need to refactor it a bit

2022-05-10 16:07 UTC, Goader reviewed
LGTM, ale najpierw trzeba ustalić co dokładnie chcemy przesyłać dla frontu

2022-05-10 16:07 UTC, Goader commented on backend/planty/dashboard/models.py
> +    def values(self):
Widziałem, że to się robi jakoś za pomocą serializer'ów, ale nie szukałem jak dokładnie ma to wyglądać. Póki co może być tak (może tak i zostanie :smile: )

2022-05-10 16:07 UTC, Goader commented on backend/planty/dashboard/views.py
> +        return Response(plant.values(), status=status.HTTP_200_OK)
`plant.values()` ma w sobie datę ostatniego podlania itp, czy tego potrzebujemy? Raczej powinniśmy przekazać dane o najbliższych event'ach związanych z tą konkretną rośliną, żeby wyświetlić później w tym okienku z event'ami

Dobrze mówię? @Kamil153

2022-05-10 16:11 UTC, Goader commented
Co do rozrastania się appki `dashboard`, to zgadzam się, trzeba będzie zrefaktoryzować. Mamy w sumie 2 opcje:
* rozbić na mniejsze appki
* wewnątrz tej appki rozbić na większą liczbę plików (osobne pliki dla różnych view i td)

Warto by sprawdzić jak to się zazwyczaj robi w takich sytuacjach. Może da się wewnątrz appki dashboard stworzyć swoje osobne appki.

Jak by nie było, myślę, że warto to zaadresować w 3 sprincie. Moim zdaniem, na dzień dzisiejszy nie ma to dużego wpływu na pisanie kodu, a mamy jeszcze inne rzeczy do zrobienia. Chyba że backend skończy taski dużo wcześniej, to wtedy można będzie zająć się refaktoryzacją.

2022-05-17 18:39 UTC, Kamil153 requested changes
przenieść id do url params

2022-05-17 18:39 UTC, Kamil153 commented on backend/planty/dashboard/views.py
> +        serializer = PlantGetSerializer(data=request.data)
id powinno być przekazywane w path params
np. /plants/id_rosliny

https://docs.djangoproject.com/en/4.0/topics/http/urls/

w widoku masz do nich dostęp chyba przez self.args i self.kwargs

2022-05-17 18:39 UTC, Kamil153 commented on backend/planty/dashboard/urls.py
> +    path('plant/', PlantView.as_view(), name='PlantView')
`plants/` - wszystkie rosliny
`plants/<uuid:id>` - jedna roślina

2022-05-17 18:39 UTC, Kamil153 commented on backend/planty/dashboard/urls.py
> +    path('plant/', PlantView.as_view(), name='PlantView')
o url params napisałem w innym komentarzu

2022-05-17 18:39 UTC, Kamil153 commented on backend/planty/dashboard/views.py
> +        return Response(plant.values(), status=status.HTTP_200_OK)
tak, można zawrzeć tutaj też eventy, ale daty nie zaszkodzą, kiedyś można będzie je wyświetlić

2022-05-17 18:41 UTC, Kamil153 commented
> 

myślę że nie ma sensu trzymać wszystkiego w jednej apce - nic nie stoi na przeszkodzie żeby zrobić osobne apki `events`, `plants` itd

2022-05-17 18:46 UTC, Kamil153 commented on backend/planty/dashboard/views.py
> +        return Response(plant.values(), status=status.HTTP_200_OK)
po chwili zastanowienia doszedłem do wniosku że może jednak będzie lepiej zrobić osobny endpoint do eventów dla konkretnej rośliny 
np. `plants/<id>/events`

2022-05-26 00:50 UTC, Goader requested changes

2022-05-26 00:50 UTC, Goader commented on backend/planty/dashboard/views.py
> +        days_late = max(0, (date.today() - planned_fertilizing).days)
Tutaj będzie problem. `planned_fertilizing` będzie minimum `today`, więc nigdy nie dostaniesz nic więcej poza 0. Zamiast `planned_fertilizing` miałoby być `plant.last_fertilized + timedelta(plant.instruction.fertilizing)`. Podobnie wyżej

2022-05-26 00:50 UTC, Goader commented on backend/planty/dashboard/views.py
> +            'date': planned_watering,
Warto zaktualizować zgodnie z tym co zrobiłem w refactoringu w innym PR

2022-05-26 00:50 UTC, Goader commented on backend/planty/dashboard/views.py
> +            custom_events = CustomEvent.objects.filter(plant=plant)
Tutaj trzeba będzie tez dodać filtr po `happened`

2022-05-26 00:50 UTC, Goader commented on backend/planty/dashboard/views.py
> +        except CustomEvent.DoesNotExist:
Czy tutaj potrzebujemy tego? Jeśli nie znajdziemy nic, to to nie będzie raczej dla nas problem. Ja dawałem ten try except w przypadkach, gdy trzeba było zmodyfikować konkretny atrybut tego obiektu

2022-05-26 00:50 UTC, Goader commented on backend/planty/dashboard/views.py
> +            plant_json["custom_events"] = custom_events
Ja bym to wrzucał razem ze wszystkim do `"events"`

2022-05-26 01:50 UTC, Goader commented on backend/planty/dashboard/views.py
> +            'date': planned_watering,
https://github.com/Goader/planty/pull/33

2022-05-26 17:07 UTC, piotrkica commented on backend/planty/dashboard/views.py
> +            custom_events = CustomEvent.objects.filter(plant=plant)
dodane tylko trzeba wcześniej zmergować #33

2022-05-26 21:49 UTC, Goader commented on backend/planty/dashboard/views.py
> +            'id': None,
Czy tu nie powinno być jeszcze `happened=False` i `interval=???`? Żeby zawsze wysyłać podobny schemat dla event'a.

+ interval jest potrzebny do wyliczenia priority po stronie front'u. W widoku konkretnej rośliny też wyświetlają się różne kolory, jęsli priority przekracza pewną wartość.

Podobnie niżej

2022-06-02 11:55 UTC, closed without merging